root: ./

redirects:
    product/integrations/atlassian-access-integration: integrations/atlassian-access-integration.md
    product/users-and-permissions/rbac-role-based-access-control/custom-roles-and-policies: users-and-permissions/rbac-role-based-access-control/custom-roles-and-policies.md
    product/integrations/zendesk-integration: integrations/zendesk-integration.md   
    product/integrations/microsoft-intune-integration: integrations/microsoft-intune-integration.md 
    product/integrations/microsoft-365-integration: integrations/microsoft-365-integration.md
    product/integrations/linear-integration: integrations/linear-integration.md
    product/integrations/intercom-integration: integrations/intercom-integration.md
    product/integrations/zoom-integration: integrations/zoom-integration.md 
    product/api/query-api: api/query-api.md
    product/integrations/gcp-integration: integrations/gcp-integration.md
    product/getting-started/quick-start-guide: getting-started/quick-start-guide.md
    product/integrations/sentry-integration: integrations/sentry-integration.md
    product/integrations/terraform-cloud-integration: integrations/terraform-cloud-integration.md
    product/integrations/hetzner-cloud-integration: integrations/hetzner-cloud-integration.md
    resource-count-calculation: settings/pricing/resource-count-calculation.md
    product/notifications/parny-notification-channel: notifications/parny-notification-channel.md
    product/integrations/figma-integration: integrations/figma-integration.md
    product/integrations/heroku-integration: integrations/heroku-integration.md
    product/integrations/azure-integration: integrations/azure-integration.md
    product/rules/aws-config-rules-vs-resmo-rules: aws-config-rules-vs-resmo-rules.md
    product/audit-logs/audit-logs: audit-logs.md
    product/notifications/amazon-sns-notification-channel: notifications/amazon-sns-notification-channel.md
    product/integrations/docusign-integration: integrations/docusign-integration.md
    product/integrations/snowflake-integration: integrations/snowflake-integration.md
    product/integrations/fastly-integration: integrations/fastly-integration.md
    product/notifications/pagerduty-notification-channel: notifications/pagerduty-notification-channel.md
    product/guides/create-your-first-rule:	guides/create-your-first-rule.md
    product/notebooks/notebooks: notebooks/notebooks.md
    product/integrations/drata-integration: integrations/drata-integration.md
    product/users-and-permissions/sso-social-login: users-and-permissions/sso-social-login.md
    product/integrations/mongodb-integration: integrations/monosign-integration.md
    product/integrations/sonarcloud-integration: integrations/sonarcloud-integration.md
    product/integrations/gandi-integration: integrations/gandi-integration.md
    product/packs/pack-exports: packs/pack-exports.md
    product/integrations/pagerduty-integration: integrations/pagerduty-integration.md
    product/integrations/monosign-integration: integrations/monosign-integration.md
    product/resource-tags/manual-tagging: resource-tags/manual-tagging.md
    product/integrations/wizer-integration: integrations/wizer-integration.md
    product/integrations/vanta-integration: integrations/vanta-integration.md
    product/integrations/microsoft-defender-integration: integrations/microsoft-defender-integration.md
    product/integrations/aws-integration: integrations/aws-integration.md
    product/integrations/upstash-integration: integrations/upstash-integration.md
    product/queries/change-sql-queries: queries/change-sql-queries.md
    product/integrations/firebase-integration: integrations/firebase-integration.md
    product/notifications/opsgenie-notification-channel: notifications/opsgenie-notification-channel.md
    product/notifications/notification-channels: notifications/notification-channels.md
    product/integrations/sophos-integration: integrations/sophos-integration.md
    product/saas-discovery/saas-discovery-employees-dashboard: saas-discovery/saas-discovery-employees-dashboard.md
    product/notifications/jira-notification-channel: notifications/jira-notification-channel.md
    product/notifications/microsoft-teams-notification-channel: notifications/microsoft-teams-notification-channel.md
    product/integrations/new-relic-integration: integrations/new-relic-integration.md
    product/integrations/vercel-integration: integrations/vercel-integration.md
    product/users-and-permissions/user: users-and-permissions/user.md
    product/notifications/webhook-notification-channel: notifications/webhook-notification-channel.md
    product/integrations/digitalocean-integration: integrations/digitalocean-integration.md
    product/resource-groups: resource-tags/resource-groups.md
    product/saas-discovery/saas-discovery-apps-dashboard: saas-discovery/saas-discovery-apps-dashboard.md
    product/resource-groups/resource-groups: resource-groups/resource-groups.md
    product/resource-tags: resource-tags/manual-tagging.md
    product/integrations/mysql-integration: integrations/mysql-integration.md
    product/integrations/segment-integration: integrations/segment-integration.md
    product/getting-started/glossary: getting-started/glossary.md
    product/resource-tags/resource-groups: resource-tags/resource-groups.md
    product/settings/billing-policy: settings/billing-policy.md
    product/integrations/bitbucket-integration: integrations/bitbucket-integration.md
    product/integrations/datadog-integration: integrations/datadog-integration.md
    product/integrations/jumpcloud-integration: integrations/jumpcloud-integration.md
    product/integrations/okta-integration: integrations/okta-integration.md
    product/integrations/bamboohr-integration: integrations/bamboohr-integration.md
    product/notifications/email-notification-channel: notifications/email-notification-channel.md
    product/integrations/gitlab-integration: integrations/gitlab-integration.md
    product/plugins/raycast: plugins/raycast.md
    product/integrations/npm-integration:	 integrations/npm-integration.md
    product/integrations/jira-integration: integrations/jira-integration.md
    product/rules: rules/rules.md
    product/rules/rules: rules/rules.md
    product/integrations/opsgenie-integration: integrations/opsgenie-integration.md
    product/users-and-permissions/rbac-role-based-access-control: users-and-permissions/rbac-role-based-access-control.md
    product/integrations/google-workspace-integration: integrations/google-workspace-integration.md
    product/integrations/jamf-integration: integrations/jamf-integration.md
    product/integrations/mixpanel-integration: integrations/mixpanel-integration.md
    product/resources/resource-changes: resources/resource-changes.md
    product/settings/pricing: settings/pricing.md
    product/saas-discovery/chrome-browser-extension: saas-discovery/chrome-browser-extension.md
    product/packs/packs: packs/packs.md
    product/integrations/flyio: integrations/flyio.md
    product/integrations/kandji-integration: integrations/kandji-integration.md
    product/guides/query-your-first-resources: guides/query-your-first-resources.md
    product/integrations/duo-integration: integrations/duo-integration.md
    product/integrations/confluence-integration: integrations/confluence-integration.md
    product/integrations/webflow-integration: integrations/webflow-integration.md
    product/integrations/kolide-integration: integrations/kolide-integration.md
    product/integrations/kubernetes-integration: integrations/kubernetes-integration.md
    product/integrations/tenable-integration: integrations/tenable-integration.md
    product/integrations/auth0-integration: integrations/auth0-integration.md
    product/integrations/mongodb-atlas-integration: integrations/mongodb-atlas-integration.md
    product/integrations/lastpass-integration: integrations/astpass-integration.md
    product/integrations/flyio-integration:	integrations/flyio-integration.md
    product/integrations/salesforce-integration: integrations/salesforce-integration.md
    product/integrations/jotform-integration: integrations/jotform-integration.md
    product/getting-started/readme: getting-started/quick-start-guide.md
    product/integrations/microsoft-teams-integration: integrations/microsoft-teams-integration.md
    product/integrations/snyk-integration: integrations/snyk-integration.md
    product/queries/standard-sql-queries: queries/standard-sql-queries.md
    product/notifications/slack-notification-channel: notifications/slack-notification-channel.md
    product/notifications: alerts/alerts.md	
    product/integrations/upstash: integrations/upstash.md
    product/saas-discovery/saas-discovery: saas-discovery.md
    product/integrations/planetscale-integration: integrations/planetscale-integration.md
    product/integrations/cloudflare-integration: integrations/cloudflare-integration.md
    product/integrations/qualys-integration: integrations/qualys-integration.md
    product/rules/suppression: rules/suppression.md
    product/queries/sql-queries: queries/sql-queries.md
    product/integrations/trello-integration: integrations/trello-integration.md
    product/integrations/help-scout-integration: integrations/help-scout-integration.md
    product/integrations/launchdarkly-integration: integrations/launchdarkly-integration.md
    product/alerts/alerts: alerts/alerts.md
    product/integrations/godaddy-integration: integrations/godaddy-integration.md
    product/integrations/github-integration: integrations/github-integration.md
    product/integrations/custom-data-integration: integrations/custom-data-integration.md
    product/api/basics: api/basics.md
    product/integrations/google-drive-integration	: integrations/google-drive-integration.md
    product/integrations/integrations-guide: integrations/integrations-guide.md
    product/getting-started/faq: getting-started/faq.md
    product/users-and-permissions/user-roles: users-and-permissions/user-roles.md
    product/integrations/tailscale-integration: integrations/tailscale-integration.md
    product/integrations/azure-active-directory-integration: integrations/azure-active-directory-integration.md
    product/integrations/slack-integration	: integrations/slack-integration.md
    product/integrations/tinybird-integration: integrations/tinybird-integration.md
    product/integrations/brex-integration: integrations/brex-integration.md
    product/settings/accounts: settings/accounts.md
    product/queries/query-types: queries/query-types.md
    product/variables/variables: variables/variables.md
    product/integrations/azure-devops-integration: integrations/azure-devops-integration.md
    product/: getting-started/quick-start-guide.md
    product/integrations/clickhouse-integration: integrations/clickhouse-integration.md
    product/packs: packs/packs.md
    product/integrations: integrations/integrations-guide.md
    product/integrations/trivy-integration: integrations/trivy-integration.md
    product/notification-rules: alerts/alerts.md
    product/alerts:	alerts/alerts.md
    product/notification-rules/notification-rules: alerts.md
    product/integrations/kolide: integrations/kolide.md
    
    
